[package]
name = "contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []


[dependencies]


[dev-dependencies]
solana-program-test="=1.7.9"
solana-sdk="1.7.9"
